Editable code component
logicalclocks/quartz pull request #127
Opened 2021-08-02 19:25 UTC by giardiv

2021-08-06 08:09 UTC, ErmiasG requested changes

2021-08-06 08:09 UTC, ErmiasG commented on src/components/code-input/index.tsx
> +                mode: {name: mode, json: true},
I do not think mode: {name: 'yaml', json: true} make sense. Shouldn't it be mode === 'javascript' ? {name: mode, json: true} : mode;

2021-08-13 10:16 UTC, SirOibaf approved these changes

2021-08-17 16:11 UTC, ErmiasG approved these changes

2021-08-17 21:45 UTC, merged