Form Tabs
logicalclocks/quartz pull request #140
Opened 2021-09-20 11:35 UTC by guceda

# Form Tabs
Fixes: [trello#374 transformations 1](https://trello.com/c/8eaWk6Oo)

2021-10-05 14:56 UTC, deividcingolani approved these changes

2021-10-12 15:13 UTC, deividcingolani requested changes

2021-10-12 15:13 UTC, deividcingolani commented on src/components/form-tabs/form-tabs.stories.tsx
> +  console.log('submit', isAllValid);
We need to remove this console.log

2021-10-13 08:10 UTC, guceda commented on src/components/form-tabs/form-tabs.stories.tsx
> +  console.log('submit', isAllValid);
solved!

2021-10-13 10:23 UTC, deividcingolani approved these changes

2021-10-13 10:39 UTC, merged