3Kz1CHwY, abybfzqJ Header
logicalclocks/quartz pull request #18
Opened 2020-10-05 15:13 UTC by YevgenChop

- Added Avatar component/stories
- Added Header component/stories
- Added Logo component
- Added Typography components/stories

- Fixed footer bug
- Fixed first-level items are ON at the same time

2020-10-05 15:13 UTC, YevgenChop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug navigation](https://trello.com/c/3Kz1CHwY/22-bug-navigation)

2020-10-05 15:13 UTC, YevgenChop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Header](https://trello.com/c/abybfzqJ/14-header)

2020-10-06 12:12 UTC, giardiv commented
Great job, just the logo seems to be displayed strangely. Just attached the correct SVG


[white.svg.zip](https://github.com/logicalclocks/quartz/files/5333628/white.svg.zip)

<img width="229" alt="Screenshot 2020-10-06 at 14 09 52" src="https://user-images.githubusercontent.com/8116383/95199750-9beb7b80-07dd-11eb-9c37-dd68ed3e4060.png">

2020-10-06 12:26 UTC, giardiv requested changes

2020-10-06 12:26 UTC, giardiv commented on src/components/avatar/index.tsx
> +  size?: string;
For now, the avatar shall not change size. You can just remove this prop

2020-10-06 12:26 UTC, giardiv commented on src/components/avatar/index.tsx
> +  size?: string;
The siwe is set at 32px height and width

2020-10-06 12:26 UTC, giardiv commented
FYI

- the badges avatar will be updated with the dedicated [Trello card](https://trello.com/c/iJjzqRLJ/23-badges)
- great initiative to have documented the font

2020-10-06 13:39 UTC, merged