Cu 1x73an0 delete the sources folder and its icons in quartz vincent giardina
logicalclocks/quartz pull request #180
Opened 2022-01-19 11:18 UTC by giardiv

- [ ] remove the icons from /sources folder
- [ ] remore fontawesome from quartz
- [ x] support icon color and sizes

2022-01-19 11:18 UTC, giardiv commented
Task linked: [CU-1x73an0 Delete the sources folder and its icons in Quartz](https://app.clickup.com/t/1x73an0)

2022-01-19 11:23 UTC, snqb commented on src/components/icon/index.tsx
> +export enum IconColors {
what do we need this for?

2022-02-28 12:58 UTC, snqb commented on src/components/file-loader/index.tsx
> +        <Flex><Icon size="sm" icon={IconName.cross} /></Flex>
nit: this should be self-enclosing

2022-02-28 12:59 UTC, snqb requested changes
good besides `package-lock.json`

2022-03-01 13:09 UTC, snqb approved these changes

2022-03-02 08:46 UTC, giardiv commented
Waiting for dependencies updates to be merged @snqb will check it out by the end of the week

2022-04-14 12:06 UTC, snqb commented
Done in https://github.com/logicalclocks/quartz/pull/240

2022-04-14 12:06 UTC, closed without merging