Create npm-publish.yml
logicalclocks/quartz pull request #218
Opened 2022-03-15 13:04 UTC by snqb

2022-03-16 10:12 UTC, ehsan-github requested changes
I wonder why would we need this? 
seems like there is a robot app setup for publishing to GitHub Packages
https://github.com/logicalclocks/quartz/actions/workflows/pages/pages-build-deployment

2022-03-16 10:12 UTC, esonhey commented on .github/workflows/npm-publish.yml
> +      - run: npm publish
If we want to publish it publicly we have to use [`--access public` option](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#:~:text=If%20your%20npm%20package%20uses%20a%20scope%20prefix%20and%20the%20package%20is%20public%2C%20you%20need%20to%20use%20the%20option%20npm%20publish%20%2D%2Daccess%20public.)

2022-03-16 10:12 UTC, ehsan-github commented on .github/workflows/npm-publish.yml
> +          registry-url: https://registry.npmjs.org/
seems like we are just publishing to npm registry in order to publish it to GitHub Packages we would require to have it as  `'https://npm.pkg.github.com'`

2022-03-16 10:12 UTC, ehsan-github commented on .github/workflows/npm-publish.yml
> +# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
Currently, the configuration publishes to NPM registry instead of GitHub

2022-03-16 10:12 UTC, ehsan-github commented on .github/workflows/npm-publish.yml
> +      - run: npm publish
Why not use `yarn` instead of `npm` for publishing?

2022-03-16 10:12 UTC, ehsan-github commented on .github/workflows/npm-publish.yml
> +      - run: npm ci
Since we are installing packages in building project I think we don't need this line

2022-03-16 11:45 UTC, snqb commented
@ehsan-github hey, this is a generated thing, never touched anything
all for test purposes :D

2022-03-16 12:16 UTC, ehsan-github commented
> @ehsan-github hey, this is a generated thing, never touched anything all for test purposes :D

Ok then let's test ;)

2022-03-16 12:16 UTC, ehsan-github approved these changes

2022-03-17 12:19 UTC, snqb commented on .github/workflows/release.yml
> +          node-version: '14.x'
this is our `engines` version

2022-03-17 12:19 UTC, snqb commented on .github/workflows/release.yml
> +          cache: 'yarn'
need this to force using `yarn`'s cache

2022-03-17 12:30 UTC, ehsan-github approved these changes
Really great job!
Looking forward to having [commitizen](https://github.com/commitizen/cz-cli) or [commitlint](https://github.com/conventional-changelog/commitlint) and use them in action

2022-03-17 12:31 UTC, merged