fix: `Input` icons logic
logicalclocks/quartz pull request #248
Opened 2022-04-20 13:32 UTC by snqb

2022-04-20 13:33 UTC, snqb commented on src/components/icon/GetIcon.tsx
> -          height: prop(size, theme.iconSizes),
its set inside `getIcon` function

2022-04-20 13:33 UTC, snqb commented on src/components/input/index.tsx
> +          {icon && <GetIcon icon={icon} color="gray" size="sm" sx={getIconStyle}/>}
that was too big, changed per request

2022-04-20 13:33 UTC, snqb commented on src/components/input/input.stories.tsx
> +    mapping: IconName,
now users can select any icon in a dropdown

2022-04-21 06:57 UTC, ehsan-github requested changes
Not all the SVGs scale properly on size change.
I think it's better to have the size property just on the width and make the height auto
```jsx
<svg
  width={size}
  height="auto"
  viewBox="0 0 24 24" // 24/24 ratio of width/size
```
<img width="1295" alt="Screen Shot 2022-04-21 at 8 47 56 AM" src="https://user-images.githubusercontent.com/19144304/164392127-49a0aa20-f31c-4636-b755-654ca82c4dba.png">

2022-04-21 06:57 UTC, ehsan-github commented on src/components/icon/GetIcon.tsx
> -          height: prop(size, theme.iconSizes),
it's better to have the correct height/width ratio in the SVG components and here we just set the width as size, and the height to be auto-scale.
if the viewBox prop of SVG is correct then with auto-scaling you can achieve the behavior to have a ratio of 1.

2022-04-21 10:06 UTC, snqb commented
@ehsan-github this was causing some problems in `position: absolute` layouts rendering with 0 height.

The assumption is that we have 1:1 icons. Can't see a problem here. Maybe I'm missing something

2022-04-21 12:25 UTC, ehsan-github commented
> @ehsan-github this was causing some problems in `position: absolute` layouts rendering with 0 height.
> 
> The assumption is that we have 1:1 icons. Can't see a problem here. Maybe I'm missing something

Hmmm Ok, then just the issue with the svgs that has fixed width and height not using `size` prop

2022-04-25 12:54 UTC, ehsan-github approved these changes
Looks good!

2022-04-25 12:57 UTC, merged